// src/lib/cloudinaryLoader.ts
"use client";

export function getWatermarkedUrl(src: string) {
  // If it's not a Cloudinary URL, return as is
  if (!src.includes("res.cloudinary.com")) return src;

  // Configuration for the Watermark
  // 1. Text: "Generated by AI Gallery" (URL encoded)
  // 2. Font: Arial, 20px, Bold
  // 3. Color: White (co_white)
  // 4. Border: 2px Black (bo_2px_solid_black) - Ensures visibility on light backgrounds
  // 5. Opacity: 90% (o_90)
  // 6. Position: Bottom Right (g_south_east)
  // 7. Padding: 20px from edges (x_20,y_20)
  const watermarkParams = `l_text:Arial_20_bold:Generator%20X,co_white,o_90,bo_2px_solid_black,g_south_east,x_20,y_20`;

  // Inject params after "/upload/"
  return src.replace("/upload/", `/upload/${watermarkParams}/`);
}

export default function cloudinaryLoader({ src, width, quality }: { src: string; width: number; quality?: number }) {
  // If it's not a Cloudinary URL, return as is
  if (!src.includes("res.cloudinary.com")) return src;

  // Cloudinary allows us to insert transformations after "/upload/"
  // We add: f_auto (auto format), c_limit (resize but don't stretch), w_{width}, q_{quality}
  const params = [`f_auto`, `c_limit`, `w_${width}`, `q_${quality || 'auto'}`];

  const paramsString = params.join(",") + "/";

  // Insert params after "upload/"
  // Example Input: https://res.cloudinary.com/.../upload/v123/img.png
  // Example Output: https://res.cloudinary.com/.../upload/f_auto,c_limit,w_800,q_auto/v123/img.png
  return src.replace("/upload/", `/upload/${paramsString}`);
}
